const UserRole = {
  ADMIN: 'ADMIN',
  EVENT_MANAGER: 'EVENT_MANAGER',
  CUSTOMER: 'CUSTOMER'
};

const ErrorType = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
  CONFLICT_ERROR: 'CONFLICT_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
};

const ResponseType = {
  SUCCESS: 'SUCCESS',
  CREATED: 'CREATED',
  NO_CONTENT: 'NO_CONTENT'
};

module.exports = {
  UserRole,
  ErrorType,
  ResponseType
};