name: Main Workflow

on:
  push:
    branches: [main]

jobs:
    job-main-1:
        uses: NityamZWT/Event-booking-System/.github/workflows/reusable_workflow.yml@staging
        with: 
            username: Nityam Patel
        secrets:
            ENV_PRO: ${{ secrets.ENV_PROD }}