name: Resuable Workflow Example

on:
  workflow_call:
    inputs:
      username:
        description: this is taking user name.
        required: true
        type: string

jobs:
  job_1:
    runs-on: ubuntu-latest

    steps:
      - name: Print my user name
        run: echo the username is ${{inputs.username}}

  job_2:
    uses: NityamZWT/Event-Booking-System/.github/workflows/sub_reusable_workflow.yml@staging
