name: "Secrets Examples"

on:
    push:
        branches: [staging]

jobs:
    my-secrets-job:
        runs-on: ubuntu-latest

        steps:
            - name: Passing secrets as context
              run: echo "Using context:" ${{secrets.CONTEXT_SECRET}}

            - name: Passing secrets as Env Vars
              run: |
                echo "Using env: $ENV_VARIABLE"
              env:
                ENV_VARIABLE: ${{secrets.ENV_SECRET}} 