name: Service Container Examples

on:
    push:
        branches: [staging]

jobs:
    container-based-jobs:
        runs-on: ubuntu-latest
        container: node 16-bullseye
        services:
            redis:
                image: redis
