name: "workflow context example"

on:
  push:
    branches: [main]

jobs:
  My_first_context_jobs:
    name: my first context
    runs-on: ubuntu-latest

    steps:
      - name: Show Context
        run: |
          echo "Actor: ${{ github.action }}"
          echo "Branch: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "GITHUB: ${{ github.* }}"
          echo "ENV: ${{ env.* }}"
          echo "SECRETS: ${{ secrets.* }}"

